In [12]:
import numpy as np
import pandas as pd

states = ["Walking" , "Running" , "Resting"]
symbols = ["Low","Medium","High"]
obss = [2,1,0,2]
pi = np.array([0.5,0.3,0.2])
A = np.array([
    [0.6,0.3,0.1],
    [0.2,0.5,0.3],
    [0.3,0.3,0.5]
])
B = np.array([
    [0.6,0.3,0.1],
    [0.1,0.3,0.6],
    [0.7,0.2,0.1]
])
print("-------------A----------------")
print(A)
print("-------------B----------------")
print(B)
print("-------------pi----------------")
print(pi)

-------------A----------------
[[0.6 0.3 0.1]
 [0.2 0.5 0.3]
 [0.3 0.3 0.5]]
-------------B----------------
[[0.6 0.3 0.1]
 [0.1 0.3 0.6]
 [0.7 0.2 0.1]]
-------------pi----------------
[0.5 0.3 0.2]


In [13]:
p = len(obss)
q = len(states)
X = np.zeros((p,q))
print(X)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
#obss = high
X[0][0] = pi[0]*B[0][2]
X[0][1] = pi[1]*B[1][2]
X[0][2] = pi[2]*B[2][2]
print(X)

[[0.05 0.18 0.02]
 [0.   0.   0.  ]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [15]:
#obss = mid
X[1][0] = (X[0][0]*A[0][0] + X[0][1]*A[1][0] + X[0][2]*A[2][0]) * B[0][1]
X[1][1] = (X[0][0]*A[0][1] + X[0][1]*A[1][1] + X[0][2]*A[2][1]) * B[1][1]
X[1][2] = (X[0][0]*A[0][2] + X[0][1]*A[1][2] + X[0][2]*A[2][2]) * B[2][1]
print(X)

[[0.05   0.18   0.02  ]
 [0.0216 0.0333 0.0138]
 [0.     0.     0.    ]
 [0.     0.     0.    ]]


In [6]:
#obss = low
X[2][0] = (X[1][0]*A[0][0] + X[1][1]*A[1][0] + X[1][2]*A[2][0]) * B[0][0]
X[2][1] = (X[1][0]*A[0][1] + X[1][1]*A[1][1] + X[1][2]*A[2][1]) * B[1][0]
X[2][2] = (X[1][0]*A[0][2] + X[1][1]*A[1][2] + X[1][2]*A[2][2]) * B[2][0]
print(X)

[[0.05     0.18     0.02    ]
 [0.0216   0.0333   0.0138  ]
 [0.014256 0.002727 0.013335]
 [0.       0.       0.      ]]


In [9]:
#obss = high
X[3][0] = (X[2][0]*A[0][0] + X[2][1]*A[1][0] + X[2][2]*A[2][0]) * B[0][2]
X[3][1] = (X[2][0]*A[0][1] + X[2][1]*A[1][1] + X[2][2]*A[2][1]) * B[1][2]
X[3][2] = (X[2][0]*A[0][2] + X[2][1]*A[1][2] + X[2][2]*A[2][2]) * B[2][2]
print(X)

[[0.05       0.18       0.02      ]
 [0.0216     0.0333     0.0138    ]
 [0.014256   0.002727   0.013335  ]
 [0.00130995 0.00578448 0.00089112]]


In [11]:
Total_prob = np.sum(X[3])
print(Total_prob)

0.00798555


In [16]:
print("Total Probability" , Total_prob)

Total Probability 0.00798555
